// <auto-generated />
namespace kurs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addthemetocurrentuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addthemetocurrentuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201905220900216_addthemetocurrentuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
